baseURL = "https://fiidireto.online/"
languageCode = "pt-br"
title = "FII Direto"
enableRobotsTXT = true
summaryLength = 40

[pagination]
  pagerSize = 10

[taxonomies]
  ticker = "tickers"
  tag = "tags"

[params]
  description = "Resumos e análises de relatórios gerenciais de Fundos Imobiliários"
  author = "FII Direto"
  keywords = "FII, fundos imobiliários, relatórios gerenciais, shoppings, logístico, lajes corporativas"
  siteUrl = "https://fiidireto.online"
  defaultImage = "images/planilha-para-controle-de-fundos-imobiliarios.png"
  twitterSite = "@fiidireto"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section  = ["HTML", "RSS"]
  page     = ["HTML"]
  taxonomy = ["HTML"]
  term     = ["HTML"]

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  style = "github"

[[menus.main]]
  name   = "Início"
  url    = "/"
  weight = 1

[[menus.main]]
  name   = "FIIs"
  url    = "/fiis/"
  weight = 2

[[menus.main]]
  name   = "Fundo de Tijolo"
  url    = "/tags/fundo-de-tijolo/"
  parent = "FIIs"
  weight = 1

[[menus.main]]
  name   = "Fundo de Papel"
  url    = "/tags/fundo-de-papel/"
  parent = "FIIs"
  weight = 2

[[menus.main]]
  name   = "Fiagro"
  url    = "/tags/fiagro/"
  parent = "FIIs"
  weight = 3

[[menus.main]]
  name   = "FI-Infra"
  url    = "/tags/fi-infra/"
  parent = "FIIs"
  weight = 4

[[menus.main]]
  name   = "Fundos de Fundos"
  url    = "/tags/fundos-de-fundos/"
  parent = "FIIs"
  weight = 5

[[menus.main]]
  name   = "Sobre"
  url    = "/sobre/"
  weight = 10

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.7
